FROM gradle:jdk17 AS build
WORKDIR /amos
COPY --chown=gradle:gradle . /amos

EXPOSE 19191
EXPOSE 19192
EXPOSE 19193
EXPOSE 19194
EXPOSE 19291

RUN gradle connector:build

ENV EDC_FS_CONFIG=resources/configuration/bank-configuration.properties

ARG EDC_DSP_CALLBACK_ADDRESS=http://bank:19194/protocol
ARG EDC_DATAPLANE_API_PUBLIC_BASEURL=http://bank:19291/public
ARG EDC_DATAPLANE_TOKEN_VALIDATION_ENDPOINT=http://bank:19192/control/token
ENV EDC_DSP_CALLBACK_ADDRESS=${EDC_DSP_CALLBACK_ADDRESS}
ENV EDC_DATAPLANE_API_PUBLIC_BASEURL=${EDC_DATAPLANE_API_PUBLIC_BASEURL}
ENV EDC_DATAPLANE_TOKEN_VALIDATION_ENDPOINT=${EDC_DATAPLANE_TOKEN_VALIDATION_ENDPOINT}

CMD ["java", "-jar", "connector/build/libs/connector.jar"]

